package.json
pnpm-lock.yaml

npm publishing was broken since fd49d5f44db4e6a4cfb3d22b6a12902a69edd834

build: install missing dependency `@lerna-lite/publish`

---

proprietary/design-tokens/src/components/utrecht/form-control.tokens.json
proprietary/design-tokens/src/components/utrecht/form-field-error-message.tokens.json
proprietary/digid-design-tokens/token-transformer.mjs
proprietary/logius-design-tokens/token-transformer.mjs
proprietary/mijnoverheid-design-tokens/token-transformer.mjs

- form-field-error-message background color red
- max-inline-size 320px 
-  16px padding toegevoegd aan form-field-error

Add form design tokens rijkshuisstijl

---

packages/storybook/config/preview-head.html
packages/storybook/config/preview.tsx
packages/storybook/src/community/alert.md
packages/storybook/src/community/alert.stories.tsx
packages/storybook/src/community/button.md
packages/storybook/src/community/button.stories.tsx
packages/storybook/src/community/heading.md
packages/storybook/src/community/heading.stories.tsx
packages/storybook/src/community/link.md
packages/storybook/src/community/link.stories.tsx
packages/storybook/src/community/paragraph.md
packages/storybook/src/community/paragraph.stories.tsx
packages/storybook/src/documentation/introduction.mdx
packages/storybook/src/documentation/license.mdx
packages/storybook/src/documentation/notice.mdx
packages/storybook/src/logius/alert.md
packages/storybook/src/logius/button.md
packages/storybook/src/logius/heading.md
packages/storybook/src/logius/link.md
packages/storybook/src/logius/paragraph.md
pnpm-lock.yaml
proprietary/logius-design-tokens/README.md
proprietary/rivm-design-tokens/README.md
proprietary/rivm-design-tokens/src/templates/utrecht-web-components.html

De wijzigingen die @Robbert  heeft gevraagd

Setup for rijkshuisstijl

---

proprietary/design-tokens/figma/figma.tokens.json

tokens toegevoegd voor de ordered list

---

proprietary/design-tokens/figma/figma.tokens.json

Bekijk de vraag in het [canvas](https://codefornl.slack.com/docs/T68FXPFQV/F07EQD8JD1C). Die zijn van belang om deze PR goed te keuren.

tokens toegevoegd voor de side nav

---

proprietary/design-tokens/figma/figma.tokens.json

De volgende componenten zijn hierin meegenomen:
- form-field-radio-option
- radio
- radio-group
Afhankelijk van onderstaande PR waar de form-field-option-label in zit:
https://github.com/nl-design-system/rijkshuisstijl-community/pull/502

tokens toegevoegd voor alle radio componenten

---

proprietary/design-tokens/figma/figma.tokens.json

De volgende componenten zijn hierin meegenomen:
- checkbox
- checkbox-group
- form-field-checkbox-option
- form-field-option-label

tokens toegevoegd voor alle checkbox componenten

---

proprietary/design-tokens/figma/figma.tokens.json

De volgende componenten zijn hierin meegenomen:
- alert
- invalid-form-alert (bevat dezelfde tokens als de alert)

tokens toegevoegd voor de alert

---

proprietary/design-tokens/figma/figma.tokens.json

tokens toegevoegd voor de blockquote

---

proprietary/design-tokens/figma/figma.tokens.json

tokens toegevoegd voor de table

---

proprietary/design-tokens/figma/figma.tokens.json

tokens toegevoegd voor heading 1 t/m heading 6

---

proprietary/design-tokens/figma/figma.tokens.json

tokens toegevoegd voor de unordered list

---

packages/components-react/tsconfig.json
packages/storybook/package.json
packages/storybook/src/community/accordion.stories.tsx
packages/storybook/src/community/button.stories.tsx
packages/storybook/src/community/link.stories.tsx
packages/storybook/src/markdown.d.ts

chore: fixed editor errors in storybook and unit tests

---

proprietary/design-tokens/figma/figma.tokens.json

Link list toegevoegd aan de components lijst en ook de tokens toegevoegd.
Eerst moet deze component nog intern worden gecontroleerd.

tokens toegevoegd voor de link list

---

.github/workflows/continuous-deployment.yml

Use a commit hash instead of `@latest`

fix: use commit hash

---

packages/storybook/src/community/form-field-textbox.md
packages/storybook/src/community/form-field-textbox.stories.tsx
pnpm-lock.yaml
proprietary/design-tokens/figma/figma.tokens.json

De volgende componenten zijn hierin meegenomen:
- form-field
- form-field-description
- form-field-error-message
- select
- text-area
- text-input

tokens toegevoegd voor form componenten

---

packages/components-css/button/index.scss

https://github.com/nl-design-system/rijkshuisstijl-community/issues/455#issuecomment-2338418407 #470

feat(icon-only-button): fixed padding not being overwritten

---

proprietary/design-tokens/figma/figma.tokens.json

font sizes en line heights aangepast, de waardes klopte niet.

Logo update

---

packages/storybook/src/community/figure.stories.tsx

- fixed issue where the same instance of the Image Component was used.
- Changed parameter name to be more specific.
- Removed array from the caption string.

feedback: Figure

---

packages/components-css/radio/index.scss
packages/storybook/src/community/radio.stories.tsx

Feature/radio (revision)

---

packages/components-css/blockquote/_mixin.scss
packages/components-css/blockquote/index.scss
packages/components-react/src/Blockquote.tsx
packages/storybook/src/community/blockquote.stories.tsx
proprietary/design-tokens/figma/figma.tokens.json

Feature/blockquote (variations and updates)

---

apps/rhc-templates/src/app/form/page.tsx
packages/components-css/logo/_mixin.scss
packages/storybook/src/community/logo.stories.tsx
proprietary/design-tokens/figma/figma.tokens.json

feat(logo): updated logo color and figure margin after demo prep

---

packages/components-css/figure/index.scss
packages/storybook/src/community/figure.stories.tsx
proprietary/design-tokens/figma/figma.tokens.json

feat(figure): added corner border radii and image source arg in storybook for demo prep

---

packages/components-css/ordered-list/index.scss
packages/components-css/unordered-list/index.scss
proprietary/design-tokens/figma/figma.tokens.json

tokens aangepast,
margin toegevoegd.

fix: changed marker and line heights

---

packages/components-css/action-group/index.scss

Refactor/design review action group alignment 

---

apps/rhc-templates/src/app/page.tsx

Footer toegevoegd aan de rich text pagina template.

update: added footer to rich text page pagina.

---

packages/components-css/dot-badge/_mixin.scss
packages/components-css/dot-badge/index.scss
packages/components-css/index.scss
packages/components-react/src/DotBadge.test.tsx
packages/components-react/src/DotBadge.tsx
packages/components-react/src/index.ts
packages/storybook/src/community/dot-badge.md
packages/storybook/src/community/dot-padge.stories.tsx
proprietary/design-tokens/figma/figma.tokens.json

feature/ Dot Badge component

---

packages/components-css/form-field-radio-option/index.scss
packages/components-css/form/index.scss
packages/components-react/src/FormFieldRadioOption.tsx
proprietary/design-tokens/figma/figma.tokens.json

[#762 ](https://github.com/nl-design-system/rijkshuisstijl-community/issues/762)

modified radio and checkbox styling

---

packages/components-react/src/FormField.test.tsx
packages/components-react/src/FormField.tsx
packages/components-react/src/FormFieldSelect.test.tsx
packages/components-react/src/FormFieldSelect.tsx
packages/components-react/src/index.ts
packages/storybook/src/templates/collage/index.tsx

[#798 ](https://github.com/nl-design-system/rijkshuisstijl-community/issues/798)

FormField refactor

---

packages/storybook/config/preview.tsx
packages/storybook/package.json

Chromatic CSS loading issue

---

packages/components-react/src/Card.tsx
packages/components-react/src/NavBar.tsx
packages/storybook/src/templates/details/index.css
packages/storybook/src/templates/details/index.tsx
packages/storybook/src/templates/globals.css
pnpm-lock.yaml

[#519](https://github.com/nl-design-system/rijkshuisstijl-community/issues/519)
Kun je controleren of de feedback van Rozerin in #519 goed is verwerkt? [Template](https://www.figma.com/design/H4hSqpPbvFMLklDZgswwgd/NLDS---Rijkshuisstijl---Templates?node-id=4410-4998&node-type=frame&t=oVx3J2Pn7DvvDIVV-0)

restructure-details-template

---

packages/storybook/src/templates/collage/index.tsx

[#894](https://github.com/nl-design-system/rijkshuisstijl-community/issues/894)

Refactored FormField in Collage template

---

apps/rvs.rivm.nl/next-env.d.ts
packages/components-react/src/FormField.tsx
packages/components-react/src/FormFieldRadioOption.test.tsx
packages/components-react/src/FormFieldRadioOption.tsx
packages/storybook/src/templates/collage/index.tsx

[#895](https://github.com/nl-design-system/rijkshuisstijl-community/issues/895)

refactored radio-option

---

packages/components-react/src/FormField.tsx
packages/components-react/src/FormFieldCheckboxGroup.test.tsx
packages/components-react/src/FormFieldCheckboxGroup.tsx

[#896](https://github.com/nl-design-system/rijkshuisstijl-community/issues/896)

refactor formfieldcheckboxgroup

---

packages/components-react/src/Footer.test.tsx
packages/components-react/src/Footer.tsx
packages/storybook/src/community/footer.stories.tsx

FEAT: added heading levels and example in storybook

---

packages/components-react/src/Button.tsx
packages/components-react/src/NavigationListItem.tsx
packages/components-react/src/SideNavLink.tsx
packages/components-react/src/icon/Icon.tsx
packages/storybook/src/community/button.stories.tsx

feat(icon-button): fixed being unable to pass icon id or wrapped icon

---

README.md
packages/storybook/src/documentation/readme.mdx

Added documentation on how to use the components in the storybook
closes #731

onboarding documentation 

---

proprietary/design-tokens/figma/figma.tokens.json

[#461](https://github.com/nl-design-system/rijkshuisstijl-community/issues/461)

updated blockquote token types values

---

packages/components-react/src/Hero.test.tsx
packages/components-react/src/Hero.tsx
packages/storybook/src/community/hero.md
packages/storybook/src/community/hero.stories.tsx
packages/storybook/src/templates/details/index.tsx

[#925](https://github.com/nl-design-system/rijkshuisstijl-community/issues/925)

edited hero props

---

proprietary/design-tokens/figma/figma.tokens.json

https://github.com/nl-design-system/rijkshuisstijl-community/issues/965

FIX: Paragraph small attribute

---

packages/components-react/src/Footer.test.tsx
packages/components-react/src/Footer.tsx
packages/storybook/src/community/footer.stories.tsx
packages/storybook/src/templates/details/index.tsx
packages/storybook/src/templates/form/index.tsx
packages/storybook/src/templates/mijn-omgeving/index.tsx
packages/storybook/src/templates/rich-text/index.tsx

Design feedback footer uitbreiding

---

packages/components-css/src/wrapper/createSpacingCSS.js
packages/components-css/src/wrapper/index.scss

FIX: SASS @import error

---

packages/storybook/src/community/page-header.md
packages/storybook/src/community/page-header.stories.tsx

https://github.com/nl-design-system/rijkshuisstijl-community/issues/970

Added PageHeader story

---

packages/components-react/src/Alert.tsx
packages/components-react/src/Card.tsx
packages/components-react/src/Toggletip.tsx
packages/components-react/src/index.ts
packages/storybook/package.json
packages/storybook/src/community/card.stories.tsx
packages/storybook/src/community/checkbox.stories.tsx
packages/storybook/src/community/hero.stories.tsx
packages/storybook/src/community/link-list-link.stories.tsx
packages/storybook/src/community/radio.stories.tsx
packages/storybook/src/community/text-input.stories.tsx
packages/storybook/src/community/textarea.stories.tsx
packages/storybook/src/templates/collage/index.tsx
packages/storybook/src/templates/form/index.tsx

FIX: all A11y tests work

---

packages/storybook/src/community/blockquote.stories.tsx

feat(storybook): added blockquote links

---

packages/components-react/src/FileInput.tsx
packages/storybook/src/community/file-input.stories.tsx

FEAT: Preload files on FileInput

---

proprietary/design-tokens/figma/figma.tokens.json

feat: add pre-heading tokens

---

packages/components-react/src/Accordion.test.tsx
packages/storybook/src/community/accordion-usage.md
packages/storybook/src/community/accordion.stories.tsx
packages/storybook/src/community/action-group.md
packages/storybook/src/community/action-group.stories.tsx

feat(storybook): improved accordion and action-group docs and unit tests

---

packages/components-react/src/Footer.test.tsx
packages/storybook/src/community/footer.md
packages/storybook/src/community/footer.stories.tsx
packages/storybook/src/templates/details/index.tsx
packages/storybook/src/templates/form/index.tsx
packages/storybook/src/templates/mijn-omgeving/index.tsx
packages/storybook/src/templates/rich-text/index.tsx

chore: removed Rijksoverheid references from footer

---

packages/components-css/src/blockquote/_mixin.scss
packages/components-css/src/blockquote/index.scss
proprietary/design-tokens/figma/figma.tokens.json

https://github.com/nl-design-system/rijkshuisstijl-community/issues/1031

FIX: line-height issues in BlockQuote

---

packages/web-components/package.json
packages/web-components/vite.config.mjs
pnpm-lock.yaml

https://github.com/nl-design-system/rijkshuisstijl-community/issues/1149

FIX: moved copy files from vite to package.json:

---

packages/web-components/package.json
packages/web-components/src/components/ActionGroup.tsx
packages/web-components/src/components/Alert.tsx
packages/web-components/src/components/BaseComponent.tsx
packages/web-components/src/components/Button.tsx
packages/web-components/src/components/Hero.tsx
pnpm-lock.yaml

added slot logic to web copmonents

---

packages/components-css/src/action-group/index.scss
packages/storybook/helpers/merge-markdown.ts
packages/storybook/src/community/action-group.md
packages/storybook/src/community/action-group.stories.tsx

- Utrecht docs geimporteerd
- RHC tokens gebruikt

updated docs and SCSS

---

packages/components-react/src/ColumnLayout.test.tsx
packages/components-react/src/ColumnLayout.tsx
packages/components-react/src/Footer.tsx
packages/components-react/src/NavBar.tsx
packages/components-react/src/index.ts
packages/storybook/src/community/column-layout.md
packages/storybook/src/community/column-layout.stories.tsx
packages/storybook/src/community/footer.stories.tsx
packages/storybook/src/community/link-list.stories.tsx
packages/storybook/src/templates/details/index.tsx

Export columnlayout from RHC

---

.github/workflows/continuous-deployment.yml

[#1157](https://github.com/nl-design-system/rijkshuisstijl-community/issues/1157)

Remove build step from test and lint

---

packages/storybook/src/community/button.md
packages/storybook/src/community/button.stories.tsx

Added links to figma, nlds component en github.
Added categories to props
Added an example for IconButton in docs

Improved button docs

---

package.json
packages/storybook/src/web-components/button.stories.tsx
packages/web-components/src/components/ActionGroup.tsx
packages/web-components/src/components/Alert.tsx
packages/web-components/src/components/BaseComponent.tsx
packages/web-components/src/components/Button.tsx
packages/web-components/src/components/Hero.tsx

https://github.com/nl-design-system/rijkshuisstijl-community/issues/1225
Revert of using Shadow DOM again to make event listeners work

FIX: event listeners

---

packages/storybook/src/web-components/accordion.stories.tsx
packages/web-components/types/global.d.ts

https://github.com/nl-design-system/rijkshuisstijl-community/issues/1111

FIX: Storybook accordion allows objects for sections

---

.github/workflows/continuous-deployment.yml

Cancel builds if there are new pushes to the same branch.
Only cancel builds for pushes to feature branches.

ci: cancel builds if necessary

---

packages/components-css/src/footer/index.scss
packages/components-react/src/Footer.test.tsx
packages/components-react/src/Footer.tsx
packages/storybook/src/community/footer.stories.tsx
packages/storybook/src/templates/details/index.css
packages/storybook/src/templates/details/index.tsx
packages/storybook/src/templates/mijn-omgeving/index.tsx
proprietary/design-tokens/figma/figma.tokens.json

added footer update 2.0

---

packages/components-css/src/dot-badge/_mixin.scss
packages/components-css/src/message-list/_mixin.scss

fix(dot-badge): fixed sizing not matching with svg

---

packages/components-css/package.json
packages/components-css/src/skip-link/_mixin.scss
packages/components-css/src/skip-link/index.scss
packages/components-react/package.json
packages/components-react/src/SkipLink.test.tsx
packages/components-react/src/SkipLink.tsx
packages/storybook/src/community/skip-link.md
packages/storybook/src/community/skip-link.stories.tsx
pnpm-lock.yaml
proprietary/design-tokens/figma/figma.tokens.json

Refactor/ SkipLink to use nl-system-design-candidate

---

package.json
pnpm-lock.yaml
prettier.config.cjs

fix: remove prettier support for .twig files (#1298)

---

packages/storybook/src/web-components/checkbox-group.stories.tsx
packages/storybook/src/web-components/form-field-checkbox-group.stories.tsx
packages/storybook/src/web-components/form-field-checkbox-option.stories.tsx
packages/storybook/src/web-components/form-field-radio-group.stories.tsx
packages/storybook/src/web-components/form-field-radio.stories.tsx
packages/storybook/src/web-components/form-field-select.stories.tsx
packages/storybook/src/web-components/form-field-text-input.stories.tsx
packages/storybook/src/web-components/form-field-textarea.stories.tsx
packages/web-components/src/components/Card.tsx
packages/web-components/src/components/FormFieldCheckboxGroup.tsx
packages/web-components/src/components/FormFieldCheckboxOption.tsx
packages/web-components/src/components/FormFieldRadio.tsx
packages/web-components/src/components/FormFieldRadioGroup.tsx
packages/web-components/src/components/FormFieldSelect.tsx
packages/web-components/src/components/FormFieldTextInput.tsx
packages/web-components/src/components/FormFieldTextarea.tsx
packages/web-components/src/index.ts
packages/web-components/types/global.d.ts

https://github.com/nl-design-system/rijkshuisstijl-community/issues/1279

FEAT: Deel 3 - React componenten omzetten naar web componenten

---

.changeset/full-carpets-drum.md
.markdownlintignore
packages/components-react/src/Card.test.tsx
packages/components-react/src/Card.tsx
packages/storybook/src/community/card.stories.tsx

fix: card-footer-render-even-with-no-props

---

.changeset/slimy-cats-read.md
packages/web-components/package.json
packages/web-components/src/components/Accordion.tsx
packages/web-components/src/index.ts
pnpm-lock.yaml

https://github.com/nl-design-system/rijkshuisstijl-community/issues/1305

FIX: JSX seems to be recognized default now

---

.changeset/bright-brooms-cats.md
.changeset/bright-brooms-dogs.md
packages/components-twig/src/Heading.twig
packages/components-twig/src/Icon.twig
packages/storybook/package.json
packages/storybook/src/components-twig/heading-twig.stories.tsx
packages/storybook/src/components-twig/icon-twig.stories.tsx
pnpm-lock.yaml

- Added new classes.
- Reworked defaultAttribute argument for all instances.
- Fixed adding attributes to object in Twig so it outputs properly.

fix(twig): Fix components in Twig (attribute property)

---

.changeset/young-starfishes-camp.md
packages/components-twig/src/Paragraph.twig
packages/storybook/src/components-twig/paragraph-twig.stories.tsx

- Create Twig template for Paragraph
todo: Missing styling.

chore(twig,paragraph): Paragraph component in Twig

---

packages/storybook/helpers/merge-markdown.ts

Closes [#1222](https://github.com/nl-design-system/rijkshuisstijl-community/issues/1222)

added comments on markdown helpers

---

.changeset/modern-days-find.md
packages/components-twig/src/Alert.twig
packages/components-twig/src/Heading.twig
packages/components-twig/src/Icon.twig
packages/storybook/src/components-twig/alert-twig.stories.tsx

Alert component in Twig with nested icon and paragraph components.

feature/twig-alert: Alert component in Twig

---

packages/storybook/src/community/link.stories.tsx

Closes [#1309](https://github.com/nl-design-system/rijkshuisstijl-community/issues/1309)

refactored link stories

---

.changeset/petite-ghosts-love.md
packages/components-react/src/FormField.test.tsx
packages/storybook/src/community/form-field.md
packages/storybook/src/community/form-field.stories.tsx

Closes [#1256](https://github.com/nl-design-system/rijkshuisstijl-community/issues/1256)

added stories & unit tests

---

packages/storybook/src/community/form-field-checkbox-group.md
packages/storybook/src/community/form-field-checkbox-group.stories.tsx

Closes [#1258](https://github.com/nl-design-system/rijkshuisstijl-community/issues/1258)

added docs & stories

---

.changeset/famous-pots-lose.md
proprietary/design-tokens/figma/figma.tokens.json

feat(design-tokens): added fallback so that the design tokens are usable with Utrecht based components

---

.changeset/funny-toes-jump.md
packages/components-css/src/card/_mixin.scss
packages/components-react/src/Card.test.tsx
packages/components-react/src/Card.tsx
proprietary/design-tokens/figma/figma.tokens.json

https://codefornl.slack.com/archives/C01DAT4TRPF/p1742381899534329

fix(card): fixed image no longer being optional in default card variant

---

packages/storybook/src/community/action-group.md

Closes [#980](https://github.com/nl-design-system/rijkshuisstijl-community/issues/980)

modified action group docs

---

.changeset/fluffy-cooks-drive.md
packages/components-react/src/Fieldset.test.tsx
packages/components-react/src/Fieldset.tsx
packages/storybook/src/community/fieldset.md
packages/storybook/src/community/fieldset.stories.tsx

Closes [#1217](https://github.com/nl-design-system/rijkshuisstijl-community/issues/1217)

Refinement fieldset

---

.changeset/six-planes-peel.md
packages/storybook/src/community/hero.md
packages/storybook/src/community/hero.stories.tsx

Closes [#1420](https://github.com/orgs/nl-design-system/projects/59/views/1?pane=issue&itemId=102859090&issue=nl-design-system%7Crijkshuisstijl-community%7C1420)

Improve Hero component: Documentation and Stories

---

.changeset/plain-zebras-joke.md
.changeset/some-drinks-trade.md
README.md
packages/components-css/README.md
packages/components-react/README.md
packages/components-twig/README.md
packages/storybook/config/preview.tsx
packages/storybook/src/community/readme.mdx
packages/storybook/src/components-twig/readme.mdx
packages/storybook/src/icon-sets/default-icon-set.stories.tsx
packages/storybook/src/icon-sets/flag-icon-set.stories.tsx
packages/storybook/src/web-components/readme.mdx
packages/web-components/README.md

docs: documentatie problemen READMEs (#1384)

---

packages/storybook/config/preview.tsx
packages/storybook/src/community/changelog.mdx
packages/storybook/src/components-twig/changelog.mdx
packages/storybook/src/documentation/design-tokens/digid.mdx
packages/storybook/src/documentation/design-tokens/logius.mdx
packages/storybook/src/documentation/design-tokens/mijnoverheid.mdx
packages/storybook/src/documentation/design-tokens/rhc.mdx
packages/storybook/src/documentation/design-tokens/rivm.mdx
packages/storybook/src/documentation/font.mdx
packages/storybook/src/web-components/changelog.mdx

feat: changelog in storybook (#1372)

---

.changeset/three-plants-retire.md
packages/storybook/src/templates/details/index.css

Closes [#1479](https://github.com/nl-design-system/rijkshuisstijl-community/issues/1479)

fixed prefooter styling

---

.changeset/hip-bananas-search.md
packages/components-react/src/Card.test.tsx
packages/components-react/src/Card.tsx
packages/components-react/src/Image.test.tsx
packages/components-react/src/Image.tsx
packages/storybook/src/community/image.md
packages/storybook/src/community/image.stories.tsx

Closes [#1421](https://github.com/nl-design-system/rijkshuisstijl-community/issues/1421)

refinement image component

---

packages/storybook/src/community/link.stories.tsx

Closes [#1422](https://github.com/nl-design-system/rijkshuisstijl-community/issues/1422)

refined link component stories

---

.changeset/deep-chairs-chew.md
packages/components-react/src/LinkList.test.tsx
packages/storybook/src/community/link-list.md
packages/storybook/src/community/link-list.stories.tsx

Closes [#1423](https://github.com/nl-design-system/rijkshuisstijl-community/issues/1423)

Refinement link list

---

.changeset/four-carrots-pick.md
packages/components-react/src/LinkListCard.test.tsx
packages/storybook/src/community/link-list-card.md

Closes [#1424](https://github.com/nl-design-system/rijkshuisstijl-community/issues/1424)

Refinement link list card

---

packages/components-angular/src/figure-caption/figure-caption.component.html
packages/components-angular/src/figure-caption/figure-caption.component.spec.ts
packages/components-angular/src/figure-caption/figure-caption.component.ts
packages/components-angular/src/figure/figure.component.html
packages/components-angular/src/figure/figure.component.spec.ts
packages/components-angular/src/figure/figure.component.ts
packages/components-angular/src/image/image.component.html
packages/components-angular/src/image/image.component.spec.ts
packages/components-angular/src/image/image.component.ts
packages/components-angular/src/public-api.ts
packages/storybook-angular/.storybook/main.ts
packages/storybook-angular/src/stories/figure.stories.ts
packages/storybook-angular/src/stories/image.stories.ts

Figure & Image Angular

---

packages/components-angular/src/logo/logo.component.html
packages/components-angular/src/logo/logo.component.spec.ts
packages/components-angular/src/logo/logo.component.ts
packages/components-angular/src/public-api.ts
packages/storybook-angular/src/stories/logo.stories.ts

Added logo component

---

.github/ISSUE_TEMPLATE/nieuw-component.md

docs: Aanmaken issue template voor component met globale definition of done (#1586)

---

.changeset/clever-bars-rescue.md
proprietary/design-tokens/figma/figma.tokens.json

Changed the name of 'Summary List' to 'Data Summary'.

feat: add data-summary tokens

---

packages/storybook/src/templates/componenten/expandable-checkbox-group.css
packages/storybook/src/templates/componenten/expandableCheckboxGroup.tsx
packages/storybook/src/templates/componenten/index.tsx

"Extra opties" in checkbox lijst.
[Preview](https://rijkshuisstijl-community-templates-git-e0fd3d-nl-design-system.vercel.app/componenten/)

Components page - extra options 

---

packages/storybook-angular/src/stories/form-field-text-input.stories.ts
packages/storybook-angular/src/stories/text-input.stories.ts

Oplossing voor [#1629](https://github.com/nl-design-system/rijkshuisstijl-community/issues/1629)
Closes #1629

Use relative imports instead of @scope in stories

---

packages/storybook/src/templates/componenten/DataBadgeButton.tsx
packages/storybook/src/templates/componenten/expandableCheckboxGroup.tsx
packages/storybook/src/templates/componenten/index.css
packages/storybook/src/templates/componenten/index.tsx
packages/storybook/src/templates/globals.css
pnpm-lock.yaml

[🔗 Preview](https://rijkshuisstijl-community-templates-git-e67361-nl-design-system.vercel.app/componenten/)
---
Add a clickable DataBadge for filtering the components.
* add `DataBadgeButton.tsx`
* changes in `index.tsx`
* changes in `index.css `
* changes in `expandableCheckboxGroup.tsx`
* merge conflicts met main opgelost (checkboxes, filter button, meer opties en de dataBadgeButtons werken nu zoals verwacht)
* "minder opties" toegevoegd aan expandableCheckboxGroup
* improved accessibility (SR)

Feat/filter badge components (DataBadgeButton)

---

.github/DISCUSSION_TEMPLATE/vraag-en-antwoord.yml

feat: aanmaken vraag en antwoord template voor github discussions (#1743)

---

.changeset/strong-squids-double.md
packages/components-react/src/NavBar.test.tsx
packages/components-react/src/NavBar.tsx
packages/storybook/src/templates/shared/header.tsx

Ik zag een todo met wat gekke code dus die wou ik aanpakken waarnaa ik merkte dat de classnames van de navbar items niet doorgevoerd werden. 
in deze pr nu opgelost.

navbar boy scouting

---

.changeset/eager-webs-float.md
package.json
packages/components-css/package.json
packages/components-react/package.json
packages/storybook/config/preview.tsx
packages/storybook/src/community/alert.stories.tsx
packages/storybook/src/community/link.stories.tsx
packages/web-components/package.json
proprietary/design-tokens/package.json

Fix hot reloading for local developtment als je storybook vannuit de root draait. Let op dat de Angular storybook prat gaat als de tokens veranderen. Ik heb dit zo gelaten zodat we in iedergeval de hot reloading voor de rest goed werkt.
En nog wat boyscouting op link story controls gedaan.

1770 hot reloading in storybook repareren om de developerervaring te verbeteren

---

.changeset/little-months-tap.md
.changeset/lovely-drinks-bathe.md
packages/components-angular/src/link-list-link/link-list-link.component.html
packages/components-angular/src/link-list-link/link-list-link.component.ts
packages/storybook-angular/src/stories/link-list-link.stories.ts

fix: LinkList Angular
