proprietary/digid-design-tokens/package.json
proprietary/digid-design-tokens/token-transformer.mjs
proprietary/logius-design-tokens/package.json
proprietary/logius-design-tokens/src/figma.tokens.json
proprietary/logius-design-tokens/src/token-transformer.mjs
proprietary/logius-design-tokens/token-transformer.mjs
proprietary/mijnoverheid-design-tokens/package.json
proprietary/mijnoverheid-design-tokens/token-transformer.mjs

All token sets starting with `theme/` are now optional, you can specify one or more themes. For example:
- `themes: ['DigiD']`
- `themes: ['DigiD', 'DigiD (dark mode)']`

build: theme support with custom token-transformer

---

proprietary/design-tokens/figma/figma.tokens.json

tokens toegevoegd voor de breadcrumb

---

proprietary/design-tokens/figma/figma.tokens.json

De volgende tokens toegevoegd die ontbraken aan de Ordered en Unordered list:
```
/* --utrecht-ordered-list-margin-block-start: <length>; */
/* --utrecht-ordered-list-margin-block-end: <length>; */
/* --utrecht-ordered-list-item-padding-inline-start: <length>; */
```

ontbrekende spacing tokens toegevoegd

---

proprietary/design-tokens/figma/figma.tokens.json

- De `common/focus` aangepast naar dezelfde naming convention als alle andere common tokens en minder tokens. Deze vervolgens verwezen naar de `utrecht.focus.*` tokens.
- Alle `utrecht.focus.* `tokens toevoegen onder een mapje `utrecht/focus`
- `utrecht.pointer-target.min-size` toegevoegd in een mapje `utrecht/pointer-target`

utrecht focus plus pointer target toegevoegd

---

proprietary/design-tokens/figma/figma.tokens.json

Replaced `rhc.form-control.border-width` by `rhc.border-width.default`.
The token was linked to a non-existent Utrecht document token, which resulted in no connection.

fix: change checkbox border-width tokens

---

packages/components-css/breadcrumb-nav/index.scss
packages/components-css/checkbox/index.scss
packages/components-css/form-field/index.scss
packages/components-react/src/Checkbox.test.tsx
packages/components-react/src/Checkbox.tsx
packages/components-react/src/FormFieldCheckboxGroup.test.tsx
packages/components-react/src/FormFieldCheckboxGroup.tsx
packages/components-react/src/FormFieldCheckboxOption.test.tsx
packages/components-react/src/FormFieldCheckboxOption.tsx
packages/components-react/src/FormFieldSelect.tsx
packages/components-react/src/index.ts
packages/storybook/src/community/checkbox-group.stories.tsx
packages/storybook/src/community/checkbox.stories.tsx
packages/storybook/src/community/form-field-checkbox-group.stories.tsx
packages/storybook/src/community/form-field-checkbox-option.md
packages/storybook/src/community/form-field-checkbox-option.stories.tsx
proprietary/design-tokens/figma/figma.tokens.json

Refactor/Checkbox Components

---

packages/components-css/accordion/index.scss
proprietary/design-tokens/figma/figma.tokens.json

closes #697
Updated token: changed utrecht.accordion.button.icon.margin-inline to utrecht.accordion.button.icon.margin-block with value {rhc.space.50}

feat(accordion): fixed icon span size and stopped center alignment when there is a lot of text in the accordion

---

proprietary/design-tokens/figma/figma.tokens.json

Added a negative margin-block-start on the description 
closes #696

fix: spacing between label and description

---

packages/components-css/accordion/index.scss
proprietary/design-tokens/figma/figma.tokens.json

Updated tokens:
1. changed utrecht.accordion.button.icon.margin-inline to utrecht.accordion.button.icon.margin-block with value {rhc.space.50}
2. utrecht.accordion.color -> rhc.accordion.color
3. utrecht.accordion.row-gap -> rhc.accordion.row-gap
4. utrecht.accordion.header.margin-block-end -> rhc.accordion.header.margin-block-end
5. utrecht.accordion.header.margin-block-start -> rhc.accordion.header.margin-block-start
6. utrecht.accordion.header.margin-inline-end -> rhc.accordion.header.margin-inline-end
7. utrecht.accordion.header.margin-inline-start -> rhc.accordion.header.margin-inline-start
8. utrecht.accordion.section.border-block-end-width -> rhc.accordion.section.border-block-end-width
9. utrecht.accordion.section.border-block-width -> rhc.accordion.section.border-block-width
10. …

Feature/accordion (token renaming)

---

packages/components-css/link-list-card/index.scss
packages/components-react/src/LinkListCard.tsx
packages/storybook/src/community/link-list-card.md

Feedback van Robbert
- het is handig als je `clsx` gebruikt zodat je ook nog eigen class names kan toevoegen:
- bijv: `<LinkListCard className="large"/>`
- voorbeeld implementatie: https://github.com/nl-design-system/utrecht/blob/main/packages/component-library-react/src/Document.tsx#L13
- `rhc-link-list__card` is niet een logische bem class name. `__element` is bedoeld voor een onderdeel van een groter component, terwijl deze component een wrapper is. `rhc-link-list-card` is beter. Zie https://getbem.com
- `heading: string;` staat geen rich text toe zoals `<sub>` voor H<sub>2</sub>O. Je kunt beter `ReactNode` als type gebruiken.
- in de documentatie schrijf je over `headingText`, terwijl de property `heading` heet.

Feature/link-list-card (added feedback points)

---

packages/components-css/package.json

component-css packages is nodig om components-react packages te gebruiken

npm: Set publischConfig to public for components-css

---

apps/rhc-templates/src/app/page.tsx

De ButtonLink componenten in de template hadden geen href, waardoor je de focus state niet kon zien.

Je kan nu de ButtonLink focus state zien in de template

---

packages/components-css/link-list/index.scss

FIX: icon infront of link is now correctly aligned with label

---

apps/rhc-templates/src/app/form/page.tsx
pnpm-lock.yaml

#[#763](https://github.com/nl-design-system/rijkshuisstijl-community/issues/763)
- Radio buttons op de [form pagina](https://rijkshuisstijl-community-templates.vercel.app/form) hebben nu een name property, waardoor je er maar één kan selecteren.
- De styling van `rhc-radio-group` word nu toegepast.

radio group

---

apps/rhc-templates/src/app/details/page.tsx

Op de details template pagina werd nog de UtrechtIcon gebruikt ipv de rhc community versie

Removed Utrecht icon from template

---

.github/dependabot.yml

Idee is om het later te groeperen als we een beter beeld hebben van welke packages zich niet aan de regels houden betreft breaking changes in patch/minor versies, dan houden we die buiten deze groep

chore(pipelines): disabled dependabot grouping since multiple dependencies don't follow patch-minor-major versioning standards

---

package.json
packages/components-react/rollup.config.mjs
packages/components-react/tsconfig.dev.json

> this script builds the project but ignores some eslint rules for development.
You can run t by running :` pnpm build:dev`
closes #814

added a build:dev script

---

packages/components-css/src/side-nav/index.scss
packages/components-react/src/SideNav.test.tsx
packages/components-react/src/SideNav.tsx
packages/components-react/src/SideNavItem.test.tsx
packages/components-react/src/SideNavLink.test.tsx
packages/storybook/src/community/side-nav-link.stories.tsx
proprietary/design-tokens/figma/figma.tokens.json

antwoord de design review taak #651 per deze [comment](https://github.com/nl-design-system/rijkshuisstijl-community/issues/651#issuecomment-2444369137)
- Reorder de stories
- Voeg een icoon toe aan alle stories
- Zorg ervoor dat `focus-visible` werkt
- Het laatste probleem: "Wanneer je naar een specifieke staat gaat, wordt deze toegepast op alle stories in het default tab. " Dit is een bug in de [plugin](https://www.npmjs.com/package/storybook-addon-pseudo-states). k heb geen oplossing kunnen vinden. Het heeft mogelijk meer onderzoek nodig, maar dit is niet gerelateerd aan de design review. Het heeft een apart taak en PR nodig als er ooit een oplossing wordt gevonden.

Refactor/answer-side-nav-design-review #651

---

packages/components-css/src/alert/index.scss
packages/components-react/src/Alert.tsx
proprietary/design-tokens/figma/figma.tokens.json

closes #959
Added tokens:
- utrecht.alert.message.line-height = {rhc.line-height.md}
- utrecht.alert.message.column-gap = {rhc.space.100}
Removed token:
- utrecht.alert.message.row-gap (unneccessary token, value is default)

feat(alert): fixed vertical alignment when there is no heading and updated tokens

---

packages/components-react/src/Alert.tsx
packages/components-react/src/FileInput.test.tsx
packages/components-react/src/FileInput.tsx
packages/storybook/config/Prettify.tsx

This commit updates the code to use the simplified ref handling introduced in React 19.
- Removed unnecessary `forwardRef` wrappers.
- Passed refs directly as props to function components.
This change simplifies the code and improves readability while taking advantage of the latest React features.

feat: Use React 19 refs

---

packages/components-css/src/pre-heading/index.scss
packages/components-react/src/FileInput.tsx

closes #831 
Tokens worden nu toegepast. CSS niet meer nodig.

Design tokens pre heading

---

packages/storybook/src/web-components/alert.stories.tsx
packages/web-components/src/components/Alert.tsx
packages/web-components/src/index.ts

#1112 
Hierbij is `textContent` een prop op ons React component, maar om dan `textContent` ook te gebruiken op ons web component geeft dit conflicten met textContent van native HTML ([bron](https://www.w3schools.com/jsref/prop_node_textcontent.asp)). Daarom is er gekozen om het `messageText` te noemen.

FEAT: Alert now also available as WC

---

packages/components-css/index.scss
packages/components-css/package.json
packages/components-css/src/number-badge/index.scss
packages/components-react/package.json
packages/components-react/src/NumberBadge.tsx
packages/storybook/src/community/number-badge.stories.tsx
pnpm-lock.yaml
proprietary/design-tokens/figma/figma.tokens.json

refactor: use Number Badge component from  @nl-design-system-candidate

---

README.md

Installation and import of font occurs in Licentie -> Fonts. User followed instructions of README and encountered "failed to resolve" error due to font being imported before install.

docs: readme states incorrectly that font can be imported before it installs in next step

---

packages/storybook/src/community/accordion.stories.tsx

Fixed een gedeelte van issue [979](https://github.com/nl-design-system/rijkshuisstijl-community/issues/979) De label, body en expanded props van een default accordion kan niet live worden aangepast via storybook en het lukt me ook niet om dit te fixen. In de Utrecht Accordion storybook kan dit ook niet voor zover ik zie dus waarschijnlijk moet dit in Utrecht Accordion component worden opgelost.

Removed Utrecht styling variant (appearance), and cleaned up args + stories

---

proprietary/design-tokens/figma/figma.tokens.json

- De value van `rhc.color.foregrond.lint` aangepast naar `rhc.color.grijs.900`
- `rhc.color.foreground.default` verwijderd
- `rhc.color.foreground.lint` hernoemd naar `rhc.color.foreground.default`
- `utrecht.document.color` value aangepast naar `rhc.color.foreground.default`
- Alle heading color tokens value's veranderd naar `rhc.color.lint-blauw.500`
- Small tokens van paragraph verwijderd, die variant heeft de nl-paragraph namelijk niet

Default fontkleur aanpassen naar zwart

---

.changeset/eager-nails-flash.md
packages/components-react/src/Card.tsx

Previously accidentally an empty div above the check, instead of wrapping the Link in the check. See https://github.com/nl-design-system/rijkshuisstijl-community/pull/1303#pullrequestreview-2632662390

fix: link in card-footer should be wrapped in div

---

.changeset/package-readme-css.md
.changeset/package-readme-font.md
.changeset/package-readme-react.md
.changeset/package-readme-twig.md
.changeset/package-readme-wc.md
README.md
packages/components-css/README.md
packages/components-react/README.md
packages/components-twig/README.md
packages/font/README.md
packages/web-components/README.md

Zoals beschreven in #1308 willen we components-twig documenteren. In plaats van een lange README te maken met alle framework(less) implementaties, hebben we de implementatie informatie verplaatst naar de README van de package. Dit zorgt er ook voor dat de package op npm netjes informatie bevat. Zie ticket voor alle informatie.
Graag ontvang ik feedback van het team op:
- Wat vind je van deze opzet? Voegt het waarde toe, of juist niet? Zou je het anders doen?
- Is de informatie correct? Voor React heb ik het enkel aangevuld. Voor Twig, CSS en Web Components heb ik het geschreven.
Closes #1308

feat(readme): split and append implementation to packages readmes (#1308)

---

.changeset/small-news-lose.md
packages/components-css/package.json
packages/components-react/package.json
packages/components-react/src/Alert.test.tsx
packages/storybook/package.json
pnpm-lock.yaml

Update dependencies `@utrecht/component-library-css` and `@utrecht/component-library-react` in order to use the updated `role` and `type` logic in Utrecht Alert component. Does not require change in our usage of Alert.
**@utrecht/component-library-css** from 7.1.5 to 7.2.1
According to [changelog](https://github.com/nl-design-system/utrecht/blob/main/packages/component-library-css/CHANGELOG.md) this is safe to update, includes:
- patch updates, including Alert update
- Add YouTube video CSS component
**@utrecht/component-library-css** from 9.0.6 to 10.1.0
According to [changelog](https://github.com/nl-design-system/utrecht/blob/main/packages/component-library-react/CHANGELOG.md) this is safe to update, includes:
- patch updates
- Alert update
- Deprecated …

feat: update utrecht component-library-css and component-library-react

---

packages/storybook-angular/src/stories/action-group.stories.ts
packages/storybook-angular/src/stories/button.stories.ts
packages/storybook-angular/src/stories/column-layout.stories.ts
packages/storybook-angular/src/stories/figure.stories.ts
packages/storybook-angular/src/stories/form-field-text-input.stories.ts
packages/storybook-angular/src/stories/heading.stories.ts
packages/storybook-angular/src/stories/icon.stories.ts
packages/storybook-angular/src/stories/image.stories.ts
packages/storybook-angular/src/stories/link-list-link.stories.ts
packages/storybook-angular/src/stories/link-list.stories.ts
packages/storybook-angular/src/stories/link.stories.ts
packages/storybook-angular/src/stories/logo.stories.ts
packages/storybook-angular/src/stories/navbar.stories.ts
packages/storybook-angular/src/stories/paragraph.stories.ts
packages/storybook-angular/src/stories/text-input.stories.ts
packages/storybook-angular/src/stories/unordered-list.stories.ts
packages/storybook/config/main.ts

- Storybook composition toegevoegd volgens Utrecht voorbeeld
- alle titles van de Angular comonenten veranderd van: Rijkshuisstijl-angular naar -> Rijkshuisstijl. Omdat als je de storybook runned ze al onder het kopje Angular components komen en het volgens mij wel duidelijk is dat als je de Angular storybook specifiek bekijkt dat het Angular componenten zijn.
Ik heb dit lokaal getest, maar ik weet niet zeker hoe ik kan testen of hij ook de production environment goed pakt, maar ik denk dat dit wel goed gaat, omdat dit een feature uit storybook zelf is en ik de Utrecht code hiervoor als voorbeeld heb genomen.
Closes #1439

Storybook composition

---

packages/storybook/src/templates/componenten/components-data.tsx

Breadcrumb-navigation data titel en heading zijn in een of ander manier geswitched. Snelle fix

refactor: titel en heading breadcrumb-navigation in components data

---

.changeset/cold-baboons-push.md
proprietary/design-tokens/figma/figma.tokens.json

Design Token type "borderStyle" does not exist, as told by Rozerin, so we change it to the suggested "other".

fix: design token type borderStyle does not exist

---

.changeset/little-stars-pick.md
packages/components-twig/package.json
pnpm-lock.yaml

Fix: Voeg `react` als peer dependency toe aan `components-twig` om Storybook builds succesvol te laten verlopen in Chromatic.
Tijdens het builden van Storybook via Chromatic kwam een fout voor omdat `react` ontbrak als peer dependency in het `components-twig` package. Hoewel `react` upstream beschikbaar is, verwacht het buildproces dat deze expliciet gedeclareerd is in de dependency chain. Door `react` als peer dependency toe te voegen, wordt de module-resolutie correct afgehandeld, waardoor de build weer slaagt.

fix: add react peer dep te components-twig

---

.changeset/blue-stars-flash.md
packages/components-css/src/alert/index.scss
packages/storybook/src/community/alert.stories.tsx

De tekstkleur van heading en paragraaf binnen Alert component laten luisteren naar `--utrecht-alert-color` zoals bedoeld.
Fixes https://github.com/nl-design-system/rijkshuisstijl-community/issues/1692

feat: alert text colors

---

.changeset/fuzzy-turkeys-ring.md
proprietary/design-tokens/figma/figma.tokens.json

https://github.com/nl-design-system/rijkshuisstijl-community/issues/1774 Cleanup based on converting to new figma library

chore: remove unused deprecated button token

---

.changeset/khaki-areas-smell.md
packages/components-css/src/navbar/index.scss

Volgens het ontwerp in Figma zou de nav bar component een border bottom moeten hebben:
Dit is nu geïmplementeerd ook in de code, zie voorbeeld:

feat: nav bar bottom border added as designed

---

.changeset/floppy-nights-do.md
packages/components-css/src/card-as-link/_mixin.scss
packages/components-css/src/card-as-link/index.scss
proprietary/design-tokens/figma/figma.tokens.json

De content neemt nu de maximale beschikbare hoogte in, zodat de CTA hyperlinks naar beneden uitgelijnd zijn.
Zie hier voorbeeld zonder wijziging:
En dit is met de wijzigingen (inline-size 100% + maximale hoogte card content):

feat: remove fixed width from component to delegate sizing to layout

---

.changeset/khaki-pans-thank.md
packages/storybook-angular/src/stories/icon.stories.ts

Er waren geen angular icon stories, waardoor het icon component niet in storybook kwam. Ook heb ik het icon in de render functie veranderd van het X logo naar een home icon.

Added default Angular Icon story

---

.github/DISCUSSION_TEMPLATE/rijkshuisstijl-2025-interpretatie.yml

Fixes https://github.com/nl-design-system/rijkshuisstijl-community/issues/1717#issuecomment-3233502456 "De template werkt niet als ik een nieuwe Discussion start. Uitzoeken waarom dit niet werkt."

fix: match github discussion category to template name #1717

---

.changeset/fancy-times-double.md
.changeset/orange-beans-shine.md
packages/components-angular/src/footer/footer.component.html
packages/storybook-angular/src/stories/footer.stories.ts
packages/storybook-angular/src/stories/link-list.stories.ts

Footer now has relative import for hot reload and added missing icons in Link list stories. The chevron icons inside the footer now get placed in the proper place in the DOM.

Misc storybook fixes

---

.changeset/silly-phones-serve.md
packages/components-react/package.json

To improve hot reloading we had references source files directly in a development environment. But this also happens in the development environments of the consuming applications where the sources files are not available.

fix: always reference dist in components react package.json

---

.changeset/chatty-worms-beg.md
packages/components-react/package.json
packages/storybook/vite.config.mjs

No longer tie the source mapping to just being in a dev environment as this would trigger for users of the package in there own developer environment causing references to non bundled source files. 
Now it will only resolve the source files if you provide the custom rhc:source condition to the build tool of the consuming package.

fix: add custom condition for source mapping
